### ISSUE TITLE
AttributeError: 

### ISSUE THREAD

**Issue by scottbrumley** [opendxl/opendxl-tie-client-python#4]

**Comment by scottbrumley** [comment]
I went to deploy some previous code that was working on GitHub that uses the TIE client.  For some reason it now gives me the following error when I try to use the set_file_reputation.  The hash I'm sending is printed out under myGetHashes.  Any help would be great.

#### TEST: SHA1 File Hash ####
     Testing http://127.0.0.1:5000/tie/getfile/?sha1=D4186881780D48BF55D4D59171B115634E3C7BA6&json=true ####
myGetHashes:
{'HashType.SHA1': u'D4186881780D48BF55D4D59171B115634E3C7BA6'}
[2017-08-17 16:17:41,050] ERROR in app: Exception on /tie/getfile/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/opendxl_web_api.py", line 384, in getFileRep
    myReturnProps = getTieRep(md5,sha1,sha256)
  File "/vagrant/opendxl_web_api.py", line 238, in getTieRep
    reputations_dict = tie_client.get_file_reputation({HashType.SHA1: "D4186881780D48BF55D4D59171B115634E3C7BA6"})
  File "/usr/local/lib/python2.7/dist-packages/dxltieclient/client.py", line 317, in get_file_reputation
    response = self.__dxl_sync_request(req)
  File "/usr/local/lib/python2.7/dist-packages/dxltieclient/client.py", line 681, in __dxl_sync_request
    res = self.__dxl_client.sync_request(request, timeout=self.__response_timeout)
  File "/usr/local/lib/python2.7/dist-packages/dxlclient-3.0.1.203-py2.7.egg/dxlclient/client.py", line 801, in sync_request
    return self._request_manager.sync_request(request, timeout)
AttributeError: 'NoneType' object has no attribute 'sync_request'
Flask Started

**Comment by chrissmith-mcafee** [comment]
Please see if you are still able to reproduce.

Thanks,
Chris
